# Generated by Django 4.0.4 on 2022-05-03 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abilitie', models.CharField(max_length=150)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Abilitie',
                'verbose_name_plural': 'User Abilities',
                'ordering': ['id'],
            },
        ),
    ]
