# Generated by Django 4.0.4 on 2022-05-03 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userabilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userabilities',
            old_name='abilitie',
            new_name='ability',
        ),
    ]
