# Generated by Django 4.0.4 on 2022-05-06 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='is_active',
        ),
    ]
