# Generated by Django 4.0.4 on 2022-05-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_active_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='driver_licens_classes',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
