# Generated by Django 4.0.4 on 2022-05-25 07:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0014_alter_artist_hospitality_raider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_duration', models.CharField(max_length=255, verbose_name='Show Duration')),
                ('price', models.CharField(max_length=255, verbose_name='Price')),
                ('payment_methods', models.CharField(max_length=100, null=True, verbose_name='Payment Methods')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('comment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Comment')),
                ('contract', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Artist Contract')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artist.artist', verbose_name='Contract artist')),
            ],
        ),
    ]
