# Generated by Django 4.0.4 on 2022-05-25 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_customercontacts_first_name'),
        ('venue', '0008_alter_venuecontacts_phone'),
        ('company', '0005_company_icon_company_terms'),
        ('contract', '0002_alter_contract_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='show_duration',
        ),
        migrations.AddField(
            model_name='contract',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venue.venue', verbose_name='Venue'),
        ),
    ]
