# Generated by Django 4.0.4 on 2022-05-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_remove_contract_show_duration_contract_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_methods',
            field=models.TextField(null=True, verbose_name='Payment Methods'),
        ),
    ]
