# Generated by Django 4.0.4 on 2022-05-29 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_contract_contract_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='contract_pdf',
            new_name='contract_pdf_url',
        ),
    ]
