# Generated by Django 4.0.4 on 2022-05-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_rename_contract_pdf_contract_contract_pdf_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='price',
            field=models.FloatField(max_length=255, verbose_name='Price'),
        ),
    ]
