# Generated by Django 4.0.4 on 2022-05-30 13:33

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_alter_contract_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='aditional_staff',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Reise', '1'), ('Hotell', '2'), ('Tono', '3'), ('Interntransport', '4'), ('Middag', '5'), ('Lunsj', '6'), ('Teknikk', '7')], max_length=54, null=True),
        ),
    ]
