# Generated by Django 4.0.4 on 2022-05-30 19:25

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_contract_aditional_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signed',
            field=models.BooleanField(default=False, null=True, verbose_name='Signed'),
        ),
        migrations.AddField(
            model_name='contract',
            name='visible',
            field=models.BooleanField(default=True, null=True, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='aditional_staff',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Reise', 'Reise'), ('Hotell', 'Hotell'), ('Tono', 'Tono'), ('Interntransport', 'Interntransport'), ('Middag', 'Middag'), ('Lunsj', 'Lunsj'), ('Teknikk', 'Teknikk')], max_length=54, null=True),
        ),
    ]
