# Generated by Django 4.0.4 on 2022-06-02 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0015_artistuserstatus'),
        ('customer', '0010_alter_customercontacts_first_name'),
        ('contract', '0009_contract_signed_contract_visible_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('artist', 'customer')},
        ),
    ]
