# Generated by Django 4.0.4 on 2022-06-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_alter_contract_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_pdf_url',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Contract PDF'),
        ),
    ]
