# Generated by Django 4.0.4 on 2022-06-07 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0011_alter_contract_contract_pdf_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractRentalProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Product name')),
                ('picture', models.FileField(upload_to='event_rental_products/', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='TimeClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Action Start Tume')),
                ('end_time', models.TimeField(verbose_name='Action End Tume')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
            ],
        ),
        migrations.CreateModel(
            name='ContractTimeClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('day_schedule', models.ManyToManyField(to='contract.timeclock', verbose_name='Day Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='ContractEventTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255, verbose_name='role')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract', verbose_name='Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Event User')),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ContractEventRentalProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('count', models.IntegerField(verbose_name='Count')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract', verbose_name='event_artists')),
                ('rental_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contractrentalproducts', verbose_name='event_rental_products')),
            ],
            options={
                'unique_together': {('event', 'rental_products')},
            },
        ),
    ]
