# Generated by Django 4.0.4 on 2022-06-08 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0013_rename_event_contracteventrentalproducts_contract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistTeamEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_team', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Artist Team')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
            ],
        ),
    ]
