# Generated by Django 4.0.4 on 2022-06-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_customernonuseredit'),
        ('artist', '0018_alter_artistuserstatus_user_access'),
        ('contract', '0014_artistteamevent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('artist', 'customer', 'date')},
        ),
    ]
