# Generated by Django 4.0.4 on 2022-06-22 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_icon_company_terms'),
        ('contract', '0015_alter_contract_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='company_products/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='CRentalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='Product Name')),
                ('in_stock', models.IntegerField(verbose_name='In stock')),
                ('price', models.FloatField(verbose_name='Price')),
                ('product_image', models.ManyToManyField(to='contract.rentalproductimage', verbose_name='RentalProductImage')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRentalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=50, verbose_name='Product Type')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company')),
                ('products', models.ManyToManyField(to='contract.crentalproduct', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyContractRentalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Product Count')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract', verbose_name='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.crentalproduct', verbose_name='Product')),
            ],
        ),
    ]
