# Generated by Django 4.0.4 on 2022-06-22 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_rentalproductimage_crentalproduct_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crentalproduct',
            options={'verbose_name': 'Rental Product', 'verbose_name_plural': 'Rental Products'},
        ),
        migrations.AlterField(
            model_name='companycontractrentalproduct',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract', verbose_name='Contract'),
        ),
    ]
