# Generated by Django 4.0.4 on 2022-06-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0017_alter_crentalproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontractrentalproduct',
            name='total_price',
            field=models.FloatField(null=True, verbose_name='Total product price'),
        ),
    ]
