# Generated by Django 4.0.4 on 2022-06-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0018_companycontractrentalproduct_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontractrentalproduct',
            name='confirmed',
            field=models.BooleanField(default=False, null=True, verbose_name='Confirmed'),
        ),
    ]
