# Generated by Django 4.0.4 on 2022-06-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0019_companycontractrentalproduct_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontractrentalproduct',
            name='company',
        ),
    ]
