# Generated by Django 4.0.4 on 2022-07-03 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0020_remove_companycontractrentalproduct_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontractrentalproduct',
            name='product',
        ),
        migrations.CreateModel(
            name='CompanyContractOneProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Product Count')),
                ('total_price', models.FloatField(null=True, verbose_name='Total product price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.crentalproduct', verbose_name='Product')),
            ],
        ),
        migrations.AddField(
            model_name='companycontractrentalproduct',
            name='products',
            field=models.ManyToManyField(to='contract.companycontractoneproduct', verbose_name='Products'),
        ),
    ]
