# Generated by Django 4.0.4 on 2022-07-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0021_remove_companycontractrentalproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontractrentalproduct',
            name='count',
            field=models.IntegerField(null=True, verbose_name='Product Count'),
        ),
    ]
