# Generated by Django 4.0.4 on 2022-07-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0023_alter_companycontractrentalproduct_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontractrentalproduct',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Product Count'),
        ),
        migrations.AlterField(
            model_name='companycontractrentalproduct',
            name='total_price',
            field=models.FloatField(default=0, verbose_name='Total product price'),
        ),
    ]
