# Generated by Django 4.0.4 on 2022-05-05 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_number', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('zip_code', models.CharField(max_length=255, verbose_name='Zip_code')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('active', models.BooleanField(default=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='user admin')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, unique=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('phone', models.CharField(max_length=255, verbose_name='phone')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('role', models.CharField(max_length=255, verbose_name='role')),
                ('birthdate', models.CharField(max_length=255, verbose_name='birth date')),
                ('signatory_rights', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='customer')),
            ],
        ),
    ]
