# Generated by Django 4.0.4 on 2022-05-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='organization_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Organization number'),
        ),
    ]
