# Generated by Django 4.0.4 on 2022-05-06 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0003_alter_customer_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='owner_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CustomerRequestsStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('granted', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='customer_on_request_storage')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_owner', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_requester', to=settings.AUTH_USER_MODEL, verbose_name='requester name')),
            ],
        ),
    ]
