# Generated by Django 4.0.4 on 2022-05-11 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_customer_owner_creator_remove_customer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccess',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='customer_access'),
        ),
    ]
