# Generated by Django 4.0.4 on 2022-05-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_customeraccess_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontacts',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email'),
        ),
    ]
