# Generated by Django 4.0.4 on 2022-05-19 11:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0008_alter_customercontacts_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customeraccess',
            unique_together={('customer', 'access')},
        ),
        migrations.AlterUniqueTogether(
            name='customerrequestsstorage',
            unique_together={('requester', 'owner', 'customer')},
        ),
    ]
