# Generated by Django 4.0.4 on 2022-05-13 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0008_alter_customercontacts_email'),
        ('venue', '0005_alter_venue_email'),
        ('artist', '0012_alter_artistaccess_artist'),
        ('company', '0003_alter_company_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('opening', models.TimeField(verbose_name='Opening Time')),
                ('closing', models.TimeField(verbose_name='Closing Time')),
                ('contract', models.TextField(verbose_name='Contract')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Customer')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.venue', verbose_name='Venue')),
            ],
        ),
        migrations.CreateModel(
            name='RentalProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Product name')),
                ('picture', models.FileField(upload_to='event_rental_products/', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='EventTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255, verbose_name='role')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event', verbose_name='Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Event User')),
            ],
        ),
        migrations.CreateModel(
            name='EventRentalProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('count', models.IntegerField(verbose_name='Count')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event', verbose_name='event_artists')),
                ('rental_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.rentalproducts', verbose_name='event_rental_products')),
            ],
        ),
        migrations.CreateModel(
            name='EventArtists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_duration', models.CharField(max_length=255, verbose_name='Show Duration')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('customers_responsibility', multiselectfield.db.fields.MultiSelectField(choices=[('Reise', 'Reise'), ('Opphold', 'Opphold'), ('Kost', 'Kost'), ('Interntransport', 'Interntransport'), ('Tono', 'Tono'), ('Technicalraider', 'Technicalraider'), ('Hospitalityrider', 'Hospitalityrider')], max_length=72)),
                ('artist', models.ManyToManyField(to='artist.artist', verbose_name='Event artist')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event', verbose_name='event_artists')),
            ],
        ),
    ]
