# Generated by Django 4.0.4 on 2022-05-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.TextField(verbose_name='Contract'),
        ),
    ]
