# Generated by Django 4.0.4 on 2022-05-15 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0012_alter_artistaccess_artist'),
        ('event', '0004_alter_event_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventartists',
            name='artist',
        ),
        migrations.AddField(
            model_name='eventartists',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artist.artist', verbose_name='Event artist'),
        ),
    ]
