# Generated by Django 4.0.4 on 2022-05-15 20:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_contract_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contract_template',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
