# Generated by Django 4.0.4 on 2022-05-23 12:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_eventartists_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventartists',
            name='contract',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Artist Contract'),
        ),
    ]
