# Generated by Django 4.0.4 on 2022-05-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_eventartists_comment_eventartists_payment_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventartists',
            name='price',
            field=models.CharField(max_length=255, verbose_name='Price'),
        ),
    ]
