# Generated by Django 4.0.4 on 2022-05-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_alter_eventartists_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventartists',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
