# Generated by Django 4.0.4 on 2022-05-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_eventartists_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='company',
        ),
        migrations.RemoveField(
            model_name='event',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='event',
            name='contract_template',
        ),
        migrations.RemoveField(
            model_name='event',
            name='customer',
        ),
        migrations.DeleteModel(
            name='EventArtists',
        ),
    ]
