# Generated by Django 4.0.4 on 2022-05-11 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('zip_code', models.CharField(max_length=255, verbose_name='Zip Code')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('capacity', models.CharField(max_length=255, verbose_name='Capacity\xa0')),
                ('opening', models.TimeField(verbose_name='Opening Time')),
                ('closing', models.TimeField(verbose_name='Closing Time')),
                ('age_limit', models.IntegerField(verbose_name='Age Limit')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('equipment', models.TextField(verbose_name='Equipment')),
                ('power', multiselectfield.db.fields.MultiSelectField(choices=[('32 Amp Blå', '32 Amp Blå'), ('32 Amp rød', '32 Amp rød'), ('63 Amp Blå', '63 Amp Blå'), ('63 Amp rød', '63 Amp rød')], max_length=43)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VenueRequestsStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('granted', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_owner', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_requester', to=settings.AUTH_USER_MODEL, verbose_name='requester name')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.venue', verbose_name='venue_on_request_storage')),
            ],
        ),
        migrations.CreateModel(
            name='VenuePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='venue_pictures/', verbose_name='Picture')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.venue', verbose_name='venue_picture')),
            ],
        ),
        migrations.CreateModel(
            name='VenueContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, unique=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('phone', models.CharField(max_length=255, verbose_name='phone')),
                ('epost', models.EmailField(max_length=255, verbose_name='email')),
                ('role', models.CharField(max_length=255, verbose_name='role')),
                ('active', models.BooleanField(default=True)),
                ('Venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.venue', verbose_name='Venue')),
            ],
        ),
        migrations.CreateModel(
            name='VenueAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='access')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.venue', verbose_name='venue_access')),
            ],
        ),
    ]
