# Generated by Django 4.0.4 on 2022-05-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_alter_venue_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venuecontacts',
            old_name='Venue',
            new_name='venue',
        ),
    ]
