# Generated by Django 4.0.4 on 2022-05-11 19:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venue', '0003_rename_venue_venuecontacts_venue'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='venueaccess',
            unique_together={('venue', 'access')},
        ),
    ]
