# Generated by Django 4.0.4 on 2022-05-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_alter_venueaccess_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email'),
        ),
    ]
