# Generated by Django 4.0.4 on 2022-05-19 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venue', '0006_alter_venue_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='equipment',
            field=models.TextField(blank=True, verbose_name='Equipment'),
        ),
        migrations.AlterUniqueTogether(
            name='venuerequestsstorage',
            unique_together={('requester', 'owner', 'venue')},
        ),
    ]
