# Generated by Django 4.0.4 on 2022-05-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0007_alter_venue_comment_alter_venue_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuecontacts',
            name='phone',
            field=models.CharField(max_length=255, unique=True, verbose_name='phone'),
        ),
    ]
