# Generated by Django 4.0.4 on 2022-06-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0008_alter_venuecontacts_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='email',
            field=models.EmailField(error_messages={'key': 'Invalid email'}, max_length=255, verbose_name='Email'),
        ),
    ]
