# Generated by Django 4.0.4 on 2022-06-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0009_alter_venue_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='email',
            field=models.CharField(error_messages={'key': 'Invalid email'}, max_length=255, verbose_name='Email'),
        ),
    ]
