# Generated by Django 4.0.4 on 2022-06-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0011_alter_venue_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuecontacts',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='venuecontacts',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='phone'),
        ),
    ]
