# Generated by Django 4.0.4 on 2022-05-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_number', models.CharField(max_length=150, verbose_name='Organozation Number')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('zip_code', models.CharField(max_length=50, verbose_name='Zip Code')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
    ]
