# Generated by Django 4.0.4 on 2022-05-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.EmailField(max_length=150, verbose_name='Address'),
        ),
    ]
