# Generated by Django 4.0.4 on 2022-05-22 12:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='icon',
            field=models.FileField(null=True, upload_to='category_image', verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='company',
            name='terms',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Terms'),
        ),
    ]
