# Generated by Django 4.0.4 on 2022-06-22 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0005_company_icon_company_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='creator',
        ),
        migrations.CreateModel(
            name='CompanyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False)),
                ('access', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='access')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='company_access')),
            ],
            options={
                'unique_together': {('company', 'access')},
            },
        ),
    ]
