# Generated by Django 4.0.4 on 2022-05-04 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('technical_raider', models.TextField(verbose_name='technical raider')),
                ('hospitality_raider', models.TextField(verbose_name='technical raider')),
                ('active', models.BooleanField(default=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='users can edit')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='artist_assets')),
                ('credit', models.CharField(max_length=255, verbose_name='credit')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist', verbose_name='artist_access')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False)),
                ('access', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist', verbose_name='artist_access')),
            ],
        ),
    ]
