# Generated by Django 4.0.4 on 2022-05-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_artistrequestsstorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistrequestsstorage',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artistrequestsstorage',
            name='granted',
            field=models.BooleanField(default=False),
        ),
    ]
