# Generated by Django 4.0.4 on 2022-05-06 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artist', '0007_artistrequestsstorage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='owner_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
