# Generated by Django 4.0.4 on 2022-05-08 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0009_alter_artistaccess_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistaccess',
            name='artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artist.artist', verbose_name='artist_access'),
        ),
    ]
