# Generated by Django 4.0.4 on 2022-05-10 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0011_remove_artist_owner_creator_remove_artist_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistaccess',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist', verbose_name='artist_access'),
        ),
    ]
