# Generated by Django 4.0.4 on 2022-05-19 11:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artist', '0012_alter_artistaccess_artist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artistaccess',
            unique_together={('artist', 'access')},
        ),
        migrations.AlterUniqueTogether(
            name='artistrequestsstorage',
            unique_together={('requester', 'owner', 'artist')},
        ),
    ]
