# Generated by Django 4.0.4 on 2022-05-22 08:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0013_alter_artistaccess_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='hospitality_raider',
            field=ckeditor.fields.RichTextField(verbose_name='technical raider'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='technical_raider',
            field=ckeditor.fields.RichTextField(verbose_name='technical raider'),
        ),
    ]
