# Generated by Django 4.0.4 on 2022-06-02 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artist', '0014_alter_artist_hospitality_raider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistUserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.BooleanField(default=False)),
                ('last_added_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last Added User')),
                ('last_asset', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='artist.artistassets', verbose_name='artist assets')),
                ('user_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artistaccess')),
            ],
        ),
    ]
