# Generated by Django 4.0.4 on 2022-06-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0016_remove_artistuserstatus_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistuserstatus',
            name='invited',
            field=models.BooleanField(null=True, verbose_name='Invited'),
        ),
    ]
