# Generated by Django 4.0.4 on 2022-06-02 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0017_artistuserstatus_invited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistuserstatus',
            name='user_access',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artist.artistaccess'),
        ),
    ]
