# Generated by Django 4.0.4 on 2022-06-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0018_alter_artistuserstatus_user_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="date_created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
