# Generated by Django 4.0.4 on 2022-06-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0025_artistbusydates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistbusydates',
            name='busy_action',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
